#!/usr/bin/env bash
# Transfers a file to the server

file_path = "$1"
server_IP = "$2"
username = "$3"
ssh_key = "$4"

if [ "$#" -lt 3 ]; then
	echo "Usage: $(basename "$0")  PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ "$#" -lt 4 ]; then
	scp -o StrictHostKeyChecking=no "$file_path" "$username@$server_IP":~/
else
	scp -i "$ssh_key" StrictHostKeyChecking=no "$file_path" "$username@$server_IP":~/
fi
