#!/usr/bin/env bash
# displays the PID, along with the process name, of processes whose name contain the word bash.
pids=$(pgrep -f bash)
# Loop through PIDs to display the PID and display the name.
for pid in pids; do
	process_name=$(ps -p "$pid" -o comm=)
	echo "PID: $pid, Process Name: $process_name"
done
