#!/usr/bin/env bash
# Find the PID of the "4-to_infinity_and_beyond" process
pid=$(pgrep -f "4-to_infinity_and_beyond")

if [ -n "$pid" ]; then
	echo "Stopping 4-to_infinity_and_beyond (PID: $pid)..."
	kill -s SIGTERM "$pid"
	echo "Process terminated."
else
	echo "4-to_infinity_and_beyond is not running."
fi
