#!/usr/bin/env bash
count=1

# Use a while loop to display "Best School" 10 times
while [ $count -le 10 ]; do
	if [ $count -eq 9 ]; then
		echo -e "Best School\nHi"
	else
        	echo "Best School"
	fi
	count=$((count + 1))
done
